### ISSUE TITLE
subscription should run only when ansible_distribution == redhat

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-ansible-repositories#4]
See https://github.com/openshift/openshift-ansible/tree/d96898b3138c4d85ba8e2d8fd34734029697777c/roles/rhel_subscribe for a good role to subscribe to RHEL, inc. Satellite support.

Let's not re-invent the wheel.

**Comment by mwperina** [comment]
Katarina/Tareq could you please take a look at Openshift role and try to use best practices from it in our role?

@KKoukiou @tareqalayan

**Comment by KKoukiou** [comment]
We can't replace the whole role, because it gives more options apart from subscription manager, but in the case of subscription manager, I can replace our part of the code,
https://github.com/oVirt/ovirt-ansible-repositories/blob/8b974f8d2a976fed995e77774a2eec6237142088/tasks/rh-subscription.yml#L1-L7, with including the above mentioned role and adding it to role requirements. 
@mwperina You think it's ok to make this role have requirements outside of our organization github page?

**Comment by machacekondra** [comment]
The reason we can't currently use the dependency to role from openshift is that, we create RPMs, and they don't so we would break RPMs installation for our role. So we can't use it as depedency.

**Comment by KKoukiou** [comment]
@machacekondra thanks for the heads up.

So, we can either keep it like this, or if the openshift role has some extra functionality we can adjust ours and actually copy their code, which sounds bad, but I don't 3rd solution.

**Comment by mwperina** [comment]
Does OpenShift role include some features which we are missing? It seems to more robust (install subscription-manager if needed, register only if not registered, attach pool if not attached, ...), but that's just a first look, maybe our current code is enough.

Do we have any tests in automation for subscriptions code? If not then either let's try to add them or discuss with @stluke to test that manually for all relevant scenarios and we will know what's missing.

And afterwards we can either copy relevant parts or discuss with OpenShift team to create common rh_subscription role for both of us (if such role already doesn't exist for platform)

**Comment by KKoukiou** [comment]
@mwperina There are not tests now for subscription-manager, we use only the rpms.
